### ISSUE TITLE
Add support for LAB

### ISSUE THREAD

**Issue by atchim** [Aloso/colo#48]
I think this tool would be even more powerful with the implementation of the CIELAB color space in the `pick` subcommand. Thanks for this great tool. :><3

**Comment by Aloso** [comment]
This is planned, and I'll probably implement it next. I'm glad you like this tool!

**Comment by Aloso** [comment]
@atchim  I just released [version 0.4.1](https://github.com/Aloso/colo/releases/tag/v0.4.1), which includes a CIELAB color picker. Feedback is appreciated!

**Comment by atchim** [comment]
> @atchim I just released [version 0.4.1](https://github.com/Aloso/colo/releases/tag/v0.4.1), which includes a CIELAB color picker. Feedback is appreciated!

I really love it !! Awesome!! Working with colors now will be much easier than before. Thank you!
